name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    # Runs daily at 23:00 UTC (4 PM PDT / 3 PM PST)
    - cron: "0 23 * * *"

jobs:
  test:
    name: Test on Python 3.12
    runs-on: ubuntu-22.04
    needs: [security]
    defaults:
      run:
        working-directory: lighthouse

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        path: lighthouse

    - name: Print OS Release Info
      run: cat /etc/os-release

    - name: Debug Python manifest reachability
      run: |
        curl -I https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json
        curl -I https://github.com/actions/python-versions/releases/download/3.12.5-10375840348/python-3.12.5-linux-22.04-x64.tar.gz

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12.5'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[dev]"

    - name: Run tests with pytest
      run: |
        python -m pytest -v --tb=short

    - name: Run type checking with mypy
      run: |
        python -m mypy lighthouse/ --ignore-missing-imports

    - name: Build wheel
      run: |
        python -m pip install build
        python -m build --wheel

    - name: Upload wheel artifact
      uses: christopherhx/gitea-upload-artifact@v4
      with:
        name: lighthouse-wheel
        path: lighthouse/dist/*.whl
        retention-days: 30

  lint:
    name: Code Quality & Linting
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: lighthouse

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        path: lighthouse

    - name: Print OS Release Info
      run: cat /etc/os-release

    - name: Debug Python manifest reachability
      run: |
        curl -I https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json
        curl -I https://github.com/actions/python-versions/releases/download/3.12.5-10375840348/python-3.12.5-linux-22.04-x64.tar.gz

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12.5'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        pip install ruff pylint radon

    - name: Run Ruff linter
      run: |
        ruff check lighthouse/ tests/

    - name: Run Pylint
      run: |
        pylint lighthouse/ --disable=C0114,C0115,C0116,R0903,W0511,W0613,W0718,W0212 --max-line-length=100 --fail-under=9.0

    - name: Check code complexity with Radon
      run: |
        radon cc lighthouse/ -a -nb
        radon mi lighthouse/ -nb

  security:
    name: Security Analysis
    runs-on: ubuntu-22.04
    needs: [lint]
    defaults:
      run:
        working-directory: lighthouse

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        path: lighthouse

    - name: Print OS Release Info
      run: cat /etc/os-release

    - name: Debug Python manifest reachability
      run: |
        curl -I https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json
        curl -I https://github.com/actions/python-versions/releases/download/3.12.5-10375840348/python-3.12.5-linux-22.04-x64.tar.gz

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12.5'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install bandit pip-audit

    - name: Run Bandit security scanner
      run: |
        bandit -r lighthouse/ --severity-level medium

    - name: Check dependencies for vulnerabilities with pip-audit
      run: |
        pip install -e .
        # Build ignore flags from .pip-audit-ignores.txt if any exist
        IGNORE_FLAGS=$(grep -v '^#' .pip-audit-ignores.txt | grep -v '^$' | sed 's/^/--ignore-vuln /' | tr '\n' ' ' || true)
        if [ -n "$IGNORE_FLAGS" ]; then
          pip-audit --skip-editable $IGNORE_FLAGS
        else
          pip-audit --skip-editable
        fi
